# This ansible playbook performs setup of a
# RaspberryPi providing a tor-proxied wifi accesspoint.
#
# Call from remote:
#
#   $ ansible-playbook -i 192.168.178.13, -u pi -k setup_zwiebelkuchen.yml
#
# with the real IP used instead.
#
- hosts: all
  become: false
  become_user: root
  vars:
      - hostname: "zwiebelkuchen"

  tasks:
  - name: Update system
    become: true
    apt: upgrade=safe update_cache=yes

  - name: Install additionally needed packages
    become: true
    package:
        name: "{{ item }}"
        state: present
    with_items:
        - "rng-tools"
        - "hostapd"
        - "isc-dhcp-server"
        - "iptables-persistent"

  - name: tweak dhcpd.conf - unset preset domain-name
    become: true
    replace:
        dest: "/etc/dhcp/dhcpd.conf"
        regexp: '^option domain-name "example\.org";'
        replace: '#option domain-name "example.org";'

  - name: tweak dhcpd.conf - unset preset domain-name-servers
    become: true
    replace:
        dest: "/etc/dhcp/dhcpd.conf"
        regexp: '^option domain-name-servers (.*);$'
        replace: '#option domain-name-servers \1'

  - name: tweak dhcpd.conf - set authoritative flag
    become: true
    replace:
        dest: "/etc/dhcp/dhcpd.conf"
        regexp: '^#authoritative;$'
        replace: 'authoritative;'

  - name: tweak dhcpd.conf - add new subnet
    become: true
    blockinfile:
        dest: "/etc/dhcp/dhcpd.conf"
        block: |
            subnet 192.168.42.0 netmask 255.255.255.0 {
                   range 192.168.42.10 192.168.42.50;
                   option broadcast-address 192.168.42.255;
                   option routers 192.168.42.1;
                   default-lease-time 600;
                   max-lease-time 7200;
                   option domain-name "local";
                   option domain-name-servers 8.8.8.8, 8.8.4.4;
            }

