# This ansible playbook performs setup of a
# RaspberryPi providing a tor-proxied wifi accesspoint.
#
# Call from remote:
#
#   $ ansible-playbook -i 192.168.178.13, -u pi -k setup_zwiebelkuchen.yml
#
# with the real IP used instead.
#
# You may want to fiddle with the settings in `vars`. The DNS servers used are
# from CCC Berlin and from DigitalCourage/FoebuD
#
- hosts: all
  become: false
  become_user: root
  vars:
      - hostname: "zwiebelkuchen"
      - dns_servers: "213.73.91.35, 85.214.20.141"

  handlers:
  - name: restart dhcpd
    become: true
    service:
        name: "isc-dhcp-server"
        state: restarted
  - name: restart hostapd
    become: true
    service:
        name: "hostapd"
        state: restarted
  - name: enable ipv4 forwarding immediately
    become: true
    shell: echo 1 > /proc/sys/net/ipv4/ip_forward
  - name: save iptables
    become: true
    shell: iptables-save > /etc/iptables/rules.v4

  tasks:
  - name: Update system
    become: true
    apt: upgrade=safe update_cache=yes

  - name: Install additionally needed packages
    become: true
    package:
        name: "{{ item }}"
        state: present
    with_items:
        - "rng-tools"
        - "hostapd"
        - "isc-dhcp-server"
        - "iptables-persistent"

  #
  # Pin wlan device names
  #
  - name: pin wlan0 to builtin wifi device
    become: true
    script: install_udev_wlan0.sh
    args:
        creates: /etc/udev/rules.d/70-persistent-net.rules

  #
  # configure dhcpd
  #
  - name: tweak dhcpd.conf - unset preset domain-name
    become: true
    replace:
        dest: "/etc/dhcp/dhcpd.conf"
        regexp: '^option domain-name "example\.org";'
        replace: '#option domain-name "example.org";'
    notify: restart dhcpd

  - name: tweak dhcpd.conf - unset preset domain-name-servers
    become: true
    replace:
        dest: "/etc/dhcp/dhcpd.conf"
        regexp: '^option domain-name-servers (.*);$'
        replace: '#option domain-name-servers \1'
    notify: restart dhcpd

  - name: tweak dhcpd.conf - set authoritative flag
    become: true
    replace:
        dest: "/etc/dhcp/dhcpd.conf"
        regexp: '^#authoritative;$'
        replace: 'authoritative;'
    notify: restart dhcpd

  - name: tweak dhcpd.conf - add new subnet
    become: true
    blockinfile:
        dest: "/etc/dhcp/dhcpd.conf"
        block: |
            subnet 192.168.42.0 netmask 255.255.255.0 {
                   range 192.168.42.10 192.168.42.50;
                   option broadcast-address 192.168.42.255;
                   option routers 192.168.42.1;
                   default-lease-time 600;
                   max-lease-time 7200;
                   option domain-name "local";
                   option domain-name-servers {{ dns_servers }};
            }
    notify: restart dhcpd

  - name: set wlan1 as dhcp-serviced device
    become: true
    replace:
        dest: "/etc/default/isc-dhcp-server"
        regexp: '^INTERFACES=""'
        replace: 'INTERFACES="wlan1"'
    notify: restart dhcpd

  - name: setup static ip config for wlan1
    become: true
    copy:
        src: "interfaces.tmpl"
        dest: "/etc/network/interfaces"
        owner: root
        group: root
        mode: 0644
        backup: yes

  #
  # configure hostapd
  #
  - name: install hostapd.conf
    become: true
    copy:
        src: "hostapd.conf.tmpl"
        dest: "/etc/hostapd/hostapd.conf"
        owner: root
        group: root
        mode: 0600
        backup: yes
    notify: restart hostapd

  - name: tell hostapd.conf location
    become: true
    replace:
        dest: "/etc/default/hostapd"
        regexp: '^#DAEMON_CONF=""'
        replace: 'DAEMON_CONF="/etc/hostapd/hostapd.conf"'
    notify: restart hostapd

  - name: set hostapd.conf location in /etc/init.d
    become: true
    replace:
        dest: "/etc/init.d/hostapd"
        regexp: '^DAEMON_CONF=$'
        replace: 'DAEMON_CONF=/etc/hostapd/hostapd.conf'
    notify: restart hostapd


  #
  # setup NAT
  #
  - name: activate ipv4 forwarding at boot time
    become: true
    replace:
        dest: "/etc/sysctl.conf"
        regexp: "^#net.ipv4.ip_forward=1"
        replace: "net.ipv4.ip_forward=1"
    notify: enable ipv4 forwarding immediately

  - name: setup iptables step 1/3
    become: true
    iptables:
        table: nat
        chain: POSTROUTING
        out_interface: wlan0
        jump: MASQUERADE
    notify: save iptables

  - name: setup iptables step 2/3
    become: true
    iptables:
        chain: FORWARD
        in_interface: wlan0
        out_interface: wlan1
        ctstate: RELATED,ESTABLISHED
        jump: ACCEPT
    notify: save iptables

  - name: setup iptables step 3/3
    become: true
    iptables:
        chain: FORWARD
        in_interface: wlan1
        out_interface: wlan0
        jump: ACCEPT
    notify: save iptables

  #
  # install hostapd with realtek support
  # XXX: This must be removed in the long run
  #
  - name: fetch precompiled binary from adafruit
    become: false
    get_url:
        url: http://adafruit-download.s3.amazonaws.com/adafruit_hostapd_14128.zip
        dest: /home/{{ ansible_ssh_user }}/adafruit_hostapd.zip
        checksum: sha256:abb9eb6bf8ffd2d334f7e47c7c0c5e4f1185264baf743c0e4796163c50ad9607

  - name: unpack adafruit hostapd
    become: false
    unarchive:
        src: /home/{{ ansible_ssh_user }}/adafruit_hostapd.zip
        dest: /home/{{ ansible_ssh_user }}/
        copy: no

  - name: install hostapd replacement
    become: true
    command: rsync -c -b --suffix="-ORIG" /home/{{ ansible_user }}/hostapd /usr/sbin/hostapd
    args:
        creates: /usr/sbin/hostapd-ORIG

  #
  # activate new services
  #
  - name: activate service hostapd
    become: true
    systemd:
        name: hostapd
        state: started
        enabled: true

  - name: enable service hostapd really
    become: true
    command: update-rc.d hostapd enable

  - name: activate service isc-dhcpd-server
    become: true
    systemd:
        name: isc-dhcp-server
        state: started
        enabled: true

  - name: enable service isc-dhcp-server really
    become: true
    command: update-rc.d isc-dhcp-server enable
